=== SrirangaDigital/tattvaloka/tattvaaloka.dtd
<!ELEMENT tattvaaloka (volume*)>
<!ELEMENT volume (part*)>
<!ATTLIST volume vnum CDATA #REQUIRED>
<!ELEMENT part (entry+)>
<!ATTLIST part pnum CDATA #REQUIRED>
<!ATTLIST part month CDATA #REQUIRED>
<!ATTLIST part year CDATA #REQUIRED>
<!ELEMENT entry (title,feature,page,allauthors)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT feature (#PCDATA)>
<!ELEMENT page (#PCDATA)>
<!ELEMENT allauthors (author*)>
<!ELEMENT author (#PCDATA)>

=== SrirangaDigital/tattvaloka/tattvaloka.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tattvaaloka SYSTEM  "tattvaaloka.dtd">
<tattvaaloka>
	<volume vnum="001">
		<part pnum="01" month="04" year="1978">
			<entry>
				<title>Prayer</title>
				<feature></feature>
				<page>0001-0002</page>
				<allauthors />
			</entry>
			<entry>
				<title>"Ourselves"</title>
				<feature>Editorial</feature>
				<page>0003-0009</page>
				<allauthors />
			</entry>
			<entry>
				<title>Sankara-His Life and Works</title>
				<feature></feature>
				<page>0010-0016</page>
				<allauthors>
					<author>Krishnaswamy S. Y.</author>
				</allauthors>
			</entry>
			<entry>
				<title>The Sources of Sankara's Thought Vidyalankara</title>
				<feature></feature>
				<page>0017-0026</page>
				<allauthors>
					<author>Ramachandra Rao S. K. Prof.</author>
				</allauthors>
			</entry>
			<entry>
				<title>The Works of Adi Shankara</title>
				<feature></feature>
				<page>0027-0051</page>
				<allauthors />
			</entry>
			<entry>
				<title>Introduction</title>
				<feature></feature>
				<page>0027-0032</page>
				<allauthors />
			</entry>
			<entry>
				<title>Dasasloki</title>
				<feature></feature>
				<page>0033-0038</page>
				<allauthors>
					<author>Subbaratnam K. V.</author>
				</allauthors>
			</entry>
			<entry>
				<title>Manisha Panchakam</title>
				<feature></feature>
				<page>0039-0044</page>
				<allauthors>
					<author>Subbaratnam K. V.</author>
				</allauthors>
			</entry>
			<entry>
				<title>Ekasloki</title>
				<feature></feature>
				<page>0045-0047</page>
				<allauthors>
					<author>Vimarshananda</author>
				</allauthors>
			</entry>
			<entry>
				<title>Upadeshapanchakam</title>
				<feature></feature>
				<page>0048-0051</page>
				<allauthors>
					<author>Vimarshananda</author>
				</allauthors>
			</entry>
			<entry>
				<title>Indian Arts &amp; Science in the Vedas</title>
				<feature></feature>
				<page>0052-0061</page>
				<allauthors>
					<author>Thirugnana Sambhandham P. Prof.</author>
				</allauthors>
			</entry>
			<entry>
				<title>Sayings of the Sadguru - Discourses of Sri Sri Abhinava Vidyatheertha Mahaswamigal, Jagadguru of Sri Sarada Peetam, Sringeri</title>
				<feature></feature>
				<page>0062-0064</page>
				<allauthors />
			</entry>
			<entry>
				<title>The Vidyasankara Temple, Sringeri</title>
				<feature></feature>
				<page>0065-0070</page>
				<allauthors>
					<author>Srinivasan K. R.</author>
				</allauthors>
			</entry>
			<entry>
				<title>Book Reviews</title>
				<feature></feature>
				<page>0071-0077</page>
				<allauthors />
			</entry>
			<entry>
				<title>Our Contributors</title>
				<feature></feature>
				<page>0078-0078</page>
				<allauthors />
			</entry>
		</part>
		<part pnum="02" month="06" year="1978">
			<entry>
				<title>Prayer</title>
				<feature></feature>
				<page>0001-0004b</page>
				<allauthors />
			</entry>
			<entry>
				<title>News and Notes</title>
				<feature></feature>
				<page>0005-0008b</page>
				<allauthors />
			</entry>
			<entry>
				<title>Sankara - His Life and Works</title>
				<feature></feature>
				<page>0009-0016</page>
				<allauthors>
					<author>Krishnaswamy S. Y.</author>
				</allauthors>
			</entry>
			<entry>
				<title>Vasistha's View of Bhakti</title>
				<feature></feature>
				<page>0017-0024</page>
				<allauthors>
					<author>Kuppuswamy B. Prof.</author>
				</allauthors>
			</entry>
			<entry>
				<title>Bhakti and Advaitavedanta</title>
				<feature></feature>
				<page>0025-0036</page>
				<allauthors>
					<author>Subbaramiah D. S.</author>
				</allauthors>
			</entry>
			<entry>
				<title>Sayings of the Sadguru - Discourses of Sri Sri Abhinava Vidyatheertha Mahaswamigal, Jagadguru of Sri Sarada Peetam, Sringeri</title>
				<feature></feature>
				<page>0037-0040</page>
				<allauthors />
			</entry>
			<entry>
				<title>The Works of Adi Sankara-Brahmanuchintanam</title>
				<feature></feature>
				<page>0041-0051</page>
				<allauthors>
					<author>Vimarshananda</author>
				</allauthors>
			</entry>
			<entry>
				<title>The Vidya Sankara Temple, Sringeri</title>
				<feature></feature>
				<page>0052-0055</page>
				<allauthors>
					<author>Srinivasan K. R.</author>
				</allauthors>
			</entry>
			<entry>
				<title>Book Reviews</title>
				<feature></feature>
				<page>0056-0059</page>
				<allauthors />
			</entry>
			<entry>
				<title>As others see us</title>
				<feature></feature>
				<page>0060-0060</page>
				<allauthors>
					<author>Charles Johnston</author>
				</allauthors>
			</entry>
			<entry>
				<title>Our new Contributors</title>
				<feature></feature>
				<page>0061-0061</page>
				<allauthors />
			</entry>
		</part>
		<part pnum="03" month="08" year="1978">
			<entry>
				<title>Prayer</title>
				<feature></feature>
				<page>0001-0004</page>
				<allauthors />
			</entry>
			<entry>
				<title>Sankara His Life and Works</title>
				<feature></feature>
				<page>0005-0018</page>
				<allauthors>
					<author>Krishnaswamy S. Y. Sri</author>
				</allauthors>
			</entry>
			<entry>
				<title>An Historical Survey of the Source - Material in Advaita</title>
				<feature></feature>
				<page>0019-0030</page>
				<allauthors>
					<author>Ramachandra Rao S. K. Prof</author>
				</allauthors>
			</entry>
			<entry>
				<title>Sri Dakshinamurthy Stotram</title>
				<feature></feature>
				<page>0031-0042</page>
				<allauthors>
					<author>Subbaramaiya D. S. Sri</author>
				</allauthors>
			</entry>
			<entry>
				<title>The Place of Bhakti in Sri Sankara's Gita - Bhashya</title>
				<feature></feature>
				<page>0043-0050</page>
				<allauthors>
					<author>Raghavachar S. S. Prof.</author>
				</allauthors>
			</entry>
			<entry>
				<title>Sri Sarada Temple</title>
				<feature></feature>
				<page>0051-0056</page>
				<allauthors>
					<author>Vimarsananda Sri</author>
				</allauthors>
			</entry>
			<entry>
				<title>Philosophy for the Common Man</title>
				<feature></feature>
				<page>0057-0059</page>
				<allauthors>
					<author>Editor</author>
				</allauthors>
			</entry>
			<entry>
				<title>Sayings of the Sadguru</title>
				<feature></feature>
				<page>0060-0061</page>
				<allauthors />
			</entry>
			<entry>
				<title>As others see us</title>
				<feature></feature>
				<page>0062-0064</page>
				<allauthors>
					<author>Alain Danielon</author>
				</allauthors>
			</entry>
			<entry>
				<title>News &amp; Notes</title>
				<feature></feature>
				<page>0065-0069</page>
				<allauthors />
			</entry>
			<entry>
				<title>Our New Contributors</title>
				<feature></feature>
				<page>0070-0070</page>
				<allauthors />
			</entry>
			<entry>
				<title>Book Reviews</title>
				<feature></feature>
				<page>0071-0079</page>
				<allauthors />
			</entry>
		</part>
		<part pnum="04" month="10" year="1978">
			<entry>
				<title>Prayer</title>
				<feature></feature>
				<page>0001-0005</page>
				<allauthors />
			</entry>
			<entry>
				<title>Sri Sureswaracharya</title>
				<feature></feature>
				<page>0006-0020</page>
				<allauthors>
					<author>Venkataraman K. R. Sri.</author>
				</allauthors>
			</entry>
			<entry>
				<title>Vedic Exegesis-A New Look</title>
				<feature></feature>
				<page>0021-0032</page>
				<allauthors>
					<author>Krishnaswamy S. Y. Sri.</author>
				</allauthors>
			</entry>
			<entry>
				<title>Sri Dakshinamurthi Stotram</title>
				<feature></feature>
				<page>0033-0048</page>
				<allauthors>
					<author>Subbaramaiya D. S. Sri</author>
				</allauthors>
			</entry>
			<entry>
				<title>Vakya vs. Drik Ganita Panchangam</title>
				<feature></feature>
				<page>0049-0054</page>
				<allauthors>
					<author>Venkataramanan K. V. Sri</author>
				</allauthors>
			</entry>
			<entry>
				<title>Book Reviews</title>
				<feature></feature>
				<page>0055-0061</page>
				<allauthors>
					<author>S. Y. K.</author>
				</allauthors>
			</entry>
		</part>
		<part pnum="05" month="12" year="1978">
			<entry>
				<title>Prayer</title>
				<feature></feature>
				<page>0001-0003</page>
				<allauthors />
			</entry>
			<entry>
				<title>Acharya Sanandana (Padma Pada)</title>
				<feature></feature>
				<page>0004-0011</page>
				<allauthors />
			</entry>
			<entry>
				<title>Padmapada on Namassivaya Mantra</title>
				<feature></feature>
				<page>0012-0018</page>
				<allauthors>
					<author>Editor</author>
				</allauthors>
			</entry>
			<entry>
				<title>Padmapada's Panchapadika</title>
				<feature></feature>
				<page>0019-0023</page>
				<allauthors>
					<author>Ramachandra Rao S. K. Prof.</author>
				</allauthors>
			</entry>
			<entry>
				<title>Vedic Exegesis-A New Look</title>
				<feature></feature>
				<page>0024-0030</page>
				<allauthors>
					<author>Krishnaswamy S. Y. Sri.</author>
				</allauthors>
			</entry>
			<entry>
				<title>Sri Dakshinamurthi Stotram</title>
				<feature></feature>
				<page>0031-0038</page>
				<allauthors>
					<author>Subbaramaiya D. S. Sri</author>
				</allauthors>
			</entry>
			<entry>
				<title>Philosophy for the Common Man</title>
				<feature></feature>
				<page>0039-0040</page>
				<allauthors />
			</entry>
			<entry>
				<title>As others see us</title>
				<feature></feature>
				<page>0041-0043</page>
				<allauthors />
			</entry>
			<entry>
				<title>Sayings of the Sadguru</title>
				<feature></feature>
				<page>0044-0047</page>
				<allauthors />
			</entry>
			<entry>
				<title>Book Reviews</title>
				<feature></feature>
				<page>0048-0054</page>
				<allauthors />
			</entry>
